# Compose file which enables emulation out of the box for non-AArch64 systems.
# 
# Comes out with sane defaults, feel free to configure as needed.

version: "3"

services:
  # This is the first container and image, responsible for setting up QEMU. In the future, this
  # can be replaced with `multiarch/qemu-user-static` when it supports at least QEMU 5.0.
  setup-qemu:
    image: qemu-handler
    build:
      context: setup-qemu
      args:
        QEMU_PKG_URL: "https://kojipkgs.fedoraproject.org/packages/qemu/5.0.0/2.fc33/x86_64/qemu-user-static-5.0.0-2.fc33.x86_64.rpm"
        QEMU_PKG_HASH: "23d937fba676db4c7546b6b30469f2a7d92d480cfcf4bcd3e7fc86587dec085f"
        IMAGE_BASE: $IMAGE_BASE
    privileged: true
  # Main container, requires no elevated privileges to run. Builds NixOS.
  build-nixos:
    depends_on:
      - setup-qemu
  # Cleanup. Waits until `build-nixos` is done via a TCP socket, then cleans up any `binfmt_misc`
  # handler registered to QEMU.
  cleanup-qemu:
    image: qemu-handler
    environment:
      QEMU_CLEANUP: "y"
    privileged: true
    depends_on:
      - build-nixos
